### ISSUE TITLE
Represent the membership as an expression

### ISSUE THREAD

**Issue by hadrienk** [InseeFr/Trevas#110]
ClauseVisitor.java (43, 12) // TODO: Should be an expression so we can handle membership better and use the exceptions for undefined var etc.

```
       res := ds1[calc test := m1 * ds1#m2 + m3]
       res := ds1#m1 -> dataset with only m1.
       res := ceil(ds1#m1)
       res := ceil(ds1)
```

__TODO__
- [ ] Implement `MembershipVisitor`

**Comment by romaintailhurat** [comment]
Development for `MembershipVisitor` started on [this branch](https://github.com/InseeFr/Trevas/tree/feature/clause-visitor-getname-with-expr).

**Comment by NicoLaval** [comment]
v1.0.0
