### ISSUE TITLE
Refactor Structured / DataPoint constructors

### ISSUE THREAD

**Issue by hadrienk** [InseeFr/Trevas#115]
Structured.java (187, 12) // TODO: Remove. We can simply use a Map<String, Component> of the constructor with Collection<Component>

https://github.com/InseeFr/Trevas/blob/660914302b826a3f891ef745e6d059e05a9cff2d/vtl-model/src/main/java/fr/insee/vtl/model/Structured.java#L187-L191

**Comment by hadrienk** [comment]
See https://github.com/InseeFr/Trevas/issues/118

**Comment by NicoLaval** [comment]
Useless
