### ISSUE TITLE
Handle nullable in spark implementation

### ISSUE THREAD

**Issue by hadrienk** [InseeFr/Trevas#117]
Identifier should not be nullable. Also the in the results from engine operations (aggr, calc, etc.)

https://github.com/InseeFr/Trevas/blob/660914302b826a3f891ef745e6d059e05a9cff2d/vtl-spark/src/main/java/fr/insee/vtl/spark/SparkDataset.java#L48-L65

**Comment by FranckCo** [comment]
Depends on #97.

**Comment by NicoLaval** [comment]
`nullable` has to be mandatory or optional?

In case we opt for optional, what would be default value? `True` or `False` ?

**Comment by hadrienk** [comment]
See https://github.com/VTL-Community/VTL-Community/issues/1#issuecomment-877833561

**Comment by FranckCo** [comment]
Partially implemented in https://github.com/InseeFr/Trevas/pull/166
See #167 for next steps
