### ISSUE TITLE
comparisonOperand factorization

### ISSUE THREAD

**Issue by NicoLaval** [InseeFr/Trevas#15]
Factorization of comparison operands, which seems to be a good idea, cause antlr context strange behavior.

See [antlr issue](https://github.com/antlr/antlr4/issues/2862)

**Comment by hadrienk** [comment]
You got an answer @NicoLaval. It seems we are doing it right and that it is "by design". I let you close this issue?

**Comment by NicoLaval** [comment]
Great explanation.
