### ISSUE TITLE
sum operator not supported

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Trevas#152]

**Comment by FranckCo** [comment]
Please be more specific

**Comment by nsenave** [comment]
I've been given VTL expressions that uses the `sum` operator like this one :

```
sum(cast(<some measure>, integer))
```

The use case here is to create a new measure, with same value for each datapoint which is the sum of a certain column.

Thanks to your answer at [issue 154](https://github.com/InseeFr/Trevas/issues/154), I realize that I can not actually simply evaluate them by doing: 

```
ds := ds [calc new_measure := sum(cast(<some measure>, integer))];
```

as the group clause is mandatory with the aggregate operator.

(Thought the operator was not supported, but I was looking in the analysis operators section of the coverage documentation.)

I'll be looking for a solution on my side.

**Comment by FranckCo** [comment]
Thanks for the details. So the issue can be closed?

**Comment by nsenave** [comment]
If the VTL expression above could be satisfied with the sum analysis operator, then my issue is about asking for the coverage of this operator.

Otherwise, if this expression is incorrect in any way, I would point it out to those who sent it to me.

(I'm not VTL-fluent enough to determine in which case I am)
