### ISSUE TITLE
Investigate the possibility of implementing jupyter kernel API

### ISSUE THREAD

**Issue by hadrienk** [InseeFr/Trevas#172]
Implementing a Jupyter compatible kernel API would allow us to run VTL in notebooks. Combine with custom data loading methods this would make for a very powerful tool.

How the kernel need to be implemented needs to be investigated:

REST API
https://jupyter-kernel-gateway.readthedocs.io/en/latest/
ZMQ API 
https://jupyter-client.readthedocs.io/en/latest/messaging.html

**Comment by NicoLaval** [comment]
WIP in @InseeFrLab/Trevas-Jupyter
