### ISSUE TITLE
Union breaks roles

### ISSUE THREAD

**Issue by NicoLaval** [InseeFr/Trevas#191]
`union` operator update roles.
`IDENTIFIER` seems to be replaced by `MEASURE`

**Comment by pengfei99** [comment]
I think I know what's going wrong. I will correct it this weekend. Do you want me create a bug fix branch?

**Comment by NicoLaval** [comment]
Good news.
Yes you can, but no emergency :)
Ty

**Comment by pengfei99** [comment]
A pull request #192 has been submitted. Can be considered as solved after merge

**Comment by pengfei99** [comment]
unit test passes on local env, but failes on the github action. Need some help on github action

**Comment by NicoLaval** [comment]
See 45d692aa5d6a1697c160de3fce41f7f923446f41
