### ISSUE TITLE
Improve type search

### ISSUE THREAD

**Issue by NicoLaval** [InseeFr/Trevas#2]
See [this example](https://github.com/InseeFr/Trevas/blob/master/java-vtl-engine/src/main/java/fr/insee/vtl/engine/visitors/expression/ComparisonVisitor.java)

When an operand is not directly define in inputed g4, it seems to be impossible to access directly to `ctx.op.getType()`

**Comment by hadrienk** [comment]
Is this related to #15 ?

**Comment by NicoLaval** [comment]
This is
