### ISSUE TITLE
Invalid type for numerics

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Trevas#298]
When handling expression like:

```
WEB := WEB [calc NHAB := if (nvl(NBHAB,0)=0) then 1 else cast(NBHAB,integer)];
```

in [Kraftwerk](https://github.com/InseeFr/Kraftwerk), an error occurs:

```
invalid type Long, expected 0 to be Double
```

Note that this VTL expression is reused from the questionnaire definition (for which the used VTL implementation is TrevasJS)

<details>

<summary>The full error message in Kraftwerk</summary>

```
Script='WEB := WEB [calc NHAB := if (nvl(NBHAB,0)=0) then 1 else cast(NBHAB,integer)];'
Message='invalid type Long, expected 0 to be Double'
```

</details>

**Comment by NicoLaval** [comment]
I reproduced your use case in tests and for me there is no error.
Is your Trevas version up-to-date?

**Comment by NicoLaval** [comment]
@romaintailhurat any news?

**Comment by romaintailhurat** [comment]
Checking with the Post Processing team at Insee

**Comment by NicoLaval** [comment]
@romaintailhurat can we close?

**Comment by romaintailhurat** [comment]
Probably
