### ISSUE TITLE
Implement custom Collector

### ISSUE THREAD

**Issue by NicoLaval** [InseeFr/Trevas#32]
As `Collector.toMap` doesn't support null values, we have to deal with `collect(HashMap ...)`.

To avoid duplication, it would be better to define a cutom collector.

See [ClauseVisitor](https://github.com/InseeFr/Trevas/blob/master/vtl-engine/src/main/java/fr/insee/vtl/engine/visitors/ClauseVisitor.java) & [Dataset](https://github.com/InseeFr/Trevas/blob/master/vtl-model/src/main/java/fr/insee/vtl/model/Dataset.java) classes

**Comment by hadrienk** [comment]
Not actual anymore.
