### ISSUE TITLE
Calc with replace currently doing nothing

### ISSUE THREAD

**Issue by NicoLaval** [InseeFr/Trevas#328]
@noahboerger you reported `calc with replace currently doing nothing`.

Could you precise please?

**Comment by noahboerger** [comment]
The example i have tested is from the BdI testcases the one under "string/pattern_replacement_3".

The following statement has not been doing the expected replacement, the calculated Text_2 was just the same as Text_1:
`result:= ds1[ calc Text_2:= replace(Text_1,"[a|e|i|o|u]")];`

When i adjusted it to use the replace operator without calc it was working as expected:
`result := (replace(ds1[drop num_1],"[a|e|i|o|u]"))[rename Text_1 to Text_2];`

**Comment by NicoLaval** [comment]
Related to #334
