### ISSUE TITLE
AggrClause Count

### ISSUE THREAD

**Issue by NicoLaval** [InseeFr/Trevas#51]
VTL Reference manual says (line 2173):
Note that the count operator is used in an aggrClause without parameters, e.g.
DS_1 [ aggr Me_1 := count ( ) group by Id_1 ) ]

In VTL.g4, aggrOperatorsGrouping says expr is required:

```
aggrOperatorsGrouping:
    op =(SUM
        | AVG
        | COUNT
        | MEDIAN
        | MIN
        | MAX
        | STDDEV_POP
        | STDDEV_SAMP
        | VAR_POP
        | VAR_SAMP) LPAREN expr (groupingClause havingClause?)? RPAREN  #aggrDataset
```

We suppose we have to fix it with expr? to enable the use of count()

**Comment by FranckCo** [comment]
Issue moved to https://github.com/VTL-Community/VTL-Community/issues/10.
