### ISSUE TITLE
Implement a function abstraction

### ISSUE THREAD

**Issue by hadrienk** [InseeFr/Trevas#88]
Function abstraction for extensibility

- [ ] Signature abstraction
- [ ] Resolve function in context/binding

```java
var engine = ... 
engine.registerFunction(String::format, "format_java");
engine.registerFunction(
    (Unary<String>) (string) -> string.toLowerCase(),
    "lowercase_java"
);
```

**Comment by NicoLaval** [comment]
Is `registerMethod` implemented into https://github.com/InseeFrLab/Trevas-Jupyter the right answer?
